---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: multi-tenant-metrics-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/angelbarrera92/multi-tenant-metrics-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: multi-tenant-metrics-demo
  namespace: flux-system
spec:
  suspend: false
  interval: 1m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: multi-tenant-metrics-demo
---
