---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: multi-tenant-metrics-demo
  namespace: flux-system
  labels:
    phase: seed
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/angelbarrera92/multi-tenant-metrics-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: multi-tenant-metrics-demo-seed
  namespace: flux-system
  labels:
    phase: seed
spec:
  suspend: false
  interval: 1m0s
  path: cluster/seed
  prune: true
  sourceRef:
    kind: GitRepository
    name: multi-tenant-metrics-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: multi-tenant-metrics-demo
  namespace: flux-system
  labels:
    phase: seed
spec:
  dependsOn:
    - name: multi-tenant-metrics-demo-seed
  suspend: false
  interval: 1m0s
  path: cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: multi-tenant-metrics-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: multi-tenant-metrics-demo-tenants
  namespace: flux-system
  labels:
    phase: seed
spec:
  dependsOn:
    - name: multi-tenant-metrics-demo
  suspend: false
  interval: 1m0s
  path: cluster/tenants
  prune: true
  sourceRef:
    kind: GitRepository
    name: multi-tenant-metrics-demo
