---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../components

patches:
- target:
    labelSelector: phase!=seed
  patch: |-
    apiVersion: any
    kind: any
    metadata:
      name: any
    $patch: delete
